# Generated by Django 5.1.1 on 2024-09-28 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_previews/', verbose_name='Blog previews'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Views count'),
        ),
    ]
