# Generated by Django 5.1.1 on 2024-09-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_feedbackmessage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
    ]
