# Generated by Django 5.1.1 on 2024-09-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_feedbackmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmessage',
            name='message',
            field=models.TextField(default='No message provided', verbose_name='Message'),
            preserve_default=False,
        ),
    ]
